name = "medicare-dashboard-api"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[vars]
DATABASE_URL = ""
DATABASE_AUTH_TOKEN = ""

# Bind an R2 bucket
[[r2_buckets]]
binding = "MEDICARE_BUCKET"
bucket_name = ""
preview_bucket_name = "medicare-dev"

# Define a KV namespace for session data
[[kv_namespaces]]
binding = "SESSION_STORE"
id = ""
preview_id = "medicare-session-dev" 